### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/ecmwf_grib-feedstock#1]
I'm curious about why the build is skipped on Python 3.

I'm working on a recipe for pygrib, and I'm using this ecmwf_grib package to get the GRIB C API. I sense the python 3 limitation is due to the python wrappers built into this package. Any thoughts on how to handle providing just the C library from this package?

**Comment by ocefpaf** [comment]
@QuLogic made a patch to build `ecmwf_grib` on Python 3. (See https://github.com/SciTools/conda-recipes-scitools/commit/93dd710f63b3497520ee3becd05898704ce24e31.)

That was later on abandoned by @pelson https://github.com/SciTools/conda-recipes-scitools/commit/bb4bf39661c3e37dc0b4ae1c7bad4fc9f0013a11 due to https://github.com/SciTools/conda-recipes-scitools/issues/88.

Not sure the best way to solve this... The options are:

1.Try to fix the problem above.
2. Create a C API only package removing the `--enable-python`. I guess that only iris uses the Python bindings and I am not sure if the next version of iris will still use it.
3. Split the package into two.

If I am correct about `iris` ditching this package I vote for option 2. What do you think @pelson?

**Comment by pelson** [comment]
> If I am correct about iris ditching this package I vote for option 2.

Not that I'm aware of. ecmwf_gribapi is deprecated in favour of eccodes anyway AFAIK (just a rebadging and merging of two repos I think). Might be that we just wan to package that (I hope it supports py3k, and know it supports Windows).

I'm also OK with option 2 though. Don't know how easy it is to add the python API to a pre-compiled C API.

**Comment by dopplershift** [comment]
According to this: https://software.ecmwf.int/wiki/download/attachments/55128009/eccodes_grib_python_2016.pdf?api=v2

no Python 3 yet.

Can we make a package for the Python API that builds everything but deletes it all except the Python lib?

**Comment by ocefpaf** [comment]
> Can we make a package for the Python API that builds everything but deletes it all except the Python lib?

@dopplershift unfortunately we cannot create two packages from the same `meta.yaml` akin to spec-files, so your suggestion is the way to go. I can take a look at this next week if you don't beat me to it.

**Comment by ocefpaf** [comment]
I don't think it is worth patching it for Python 3 and the `pygrib` seems to be resolved. I am closing this but feel free to re-open if you disagree.
